// Code generated by counterfeiter. DO NOT EDIT.
package typesfakes

import (
	"sync"

	"github.com/maximilien/kn-source-pkg/pkg/types"
	"knative.dev/eventing-contrib/github/pkg/client/clientset/versioned/typed/sources/v1alpha1"
)

type FakeKnSourceClient struct {
	KnSourceParamsStub        func() *types.KnSourceParams
	knSourceParamsMutex       sync.RWMutex
	knSourceParamsArgsForCall []struct {
	}
	knSourceParamsReturns struct {
		result1 *types.KnSourceParams
	}
	knSourceParamsReturnsOnCall map[int]struct {
		result1 *types.KnSourceParams
	}
	NamespaceStub        func() string
	namespaceMutex       sync.RWMutex
	namespaceArgsForCall []struct {
	}
	namespaceReturns struct {
		result1 string
	}
	namespaceReturnsOnCall map[int]struct {
		result1 string
	}
	SourcesClientStub        func() v1alpha1.SourcesV1alpha1Interface
	sourcesClientMutex       sync.RWMutex
	sourcesClientArgsForCall []struct {
	}
	sourcesClientReturns struct {
		result1 v1alpha1.SourcesV1alpha1Interface
	}
	sourcesClientReturnsOnCall map[int]struct {
		result1 v1alpha1.SourcesV1alpha1Interface
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeKnSourceClient) KnSourceParams() *types.KnSourceParams {
	fake.knSourceParamsMutex.Lock()
	ret, specificReturn := fake.knSourceParamsReturnsOnCall[len(fake.knSourceParamsArgsForCall)]
	fake.knSourceParamsArgsForCall = append(fake.knSourceParamsArgsForCall, struct {
	}{})
	fake.recordInvocation("KnSourceParams", []interface{}{})
	fake.knSourceParamsMutex.Unlock()
	if fake.KnSourceParamsStub != nil {
		return fake.KnSourceParamsStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.knSourceParamsReturns
	return fakeReturns.result1
}

func (fake *FakeKnSourceClient) KnSourceParamsCallCount() int {
	fake.knSourceParamsMutex.RLock()
	defer fake.knSourceParamsMutex.RUnlock()
	return len(fake.knSourceParamsArgsForCall)
}

func (fake *FakeKnSourceClient) KnSourceParamsCalls(stub func() *types.KnSourceParams) {
	fake.knSourceParamsMutex.Lock()
	defer fake.knSourceParamsMutex.Unlock()
	fake.KnSourceParamsStub = stub
}

func (fake *FakeKnSourceClient) KnSourceParamsReturns(result1 *types.KnSourceParams) {
	fake.knSourceParamsMutex.Lock()
	defer fake.knSourceParamsMutex.Unlock()
	fake.KnSourceParamsStub = nil
	fake.knSourceParamsReturns = struct {
		result1 *types.KnSourceParams
	}{result1}
}

func (fake *FakeKnSourceClient) KnSourceParamsReturnsOnCall(i int, result1 *types.KnSourceParams) {
	fake.knSourceParamsMutex.Lock()
	defer fake.knSourceParamsMutex.Unlock()
	fake.KnSourceParamsStub = nil
	if fake.knSourceParamsReturnsOnCall == nil {
		fake.knSourceParamsReturnsOnCall = make(map[int]struct {
			result1 *types.KnSourceParams
		})
	}
	fake.knSourceParamsReturnsOnCall[i] = struct {
		result1 *types.KnSourceParams
	}{result1}
}

func (fake *FakeKnSourceClient) Namespace() string {
	fake.namespaceMutex.Lock()
	ret, specificReturn := fake.namespaceReturnsOnCall[len(fake.namespaceArgsForCall)]
	fake.namespaceArgsForCall = append(fake.namespaceArgsForCall, struct {
	}{})
	fake.recordInvocation("Namespace", []interface{}{})
	fake.namespaceMutex.Unlock()
	if fake.NamespaceStub != nil {
		return fake.NamespaceStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.namespaceReturns
	return fakeReturns.result1
}

func (fake *FakeKnSourceClient) NamespaceCallCount() int {
	fake.namespaceMutex.RLock()
	defer fake.namespaceMutex.RUnlock()
	return len(fake.namespaceArgsForCall)
}

func (fake *FakeKnSourceClient) NamespaceCalls(stub func() string) {
	fake.namespaceMutex.Lock()
	defer fake.namespaceMutex.Unlock()
	fake.NamespaceStub = stub
}

func (fake *FakeKnSourceClient) NamespaceReturns(result1 string) {
	fake.namespaceMutex.Lock()
	defer fake.namespaceMutex.Unlock()
	fake.NamespaceStub = nil
	fake.namespaceReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeKnSourceClient) NamespaceReturnsOnCall(i int, result1 string) {
	fake.namespaceMutex.Lock()
	defer fake.namespaceMutex.Unlock()
	fake.NamespaceStub = nil
	if fake.namespaceReturnsOnCall == nil {
		fake.namespaceReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.namespaceReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeKnSourceClient) SourcesClient() v1alpha1.SourcesV1alpha1Interface {
	fake.sourcesClientMutex.Lock()
	ret, specificReturn := fake.sourcesClientReturnsOnCall[len(fake.sourcesClientArgsForCall)]
	fake.sourcesClientArgsForCall = append(fake.sourcesClientArgsForCall, struct {
	}{})
	fake.recordInvocation("SourcesClient", []interface{}{})
	fake.sourcesClientMutex.Unlock()
	if fake.SourcesClientStub != nil {
		return fake.SourcesClientStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.sourcesClientReturns
	return fakeReturns.result1
}

func (fake *FakeKnSourceClient) SourcesClientCallCount() int {
	fake.sourcesClientMutex.RLock()
	defer fake.sourcesClientMutex.RUnlock()
	return len(fake.sourcesClientArgsForCall)
}

func (fake *FakeKnSourceClient) SourcesClientCalls(stub func() v1alpha1.SourcesV1alpha1Interface) {
	fake.sourcesClientMutex.Lock()
	defer fake.sourcesClientMutex.Unlock()
	fake.SourcesClientStub = stub
}

func (fake *FakeKnSourceClient) SourcesClientReturns(result1 v1alpha1.SourcesV1alpha1Interface) {
	fake.sourcesClientMutex.Lock()
	defer fake.sourcesClientMutex.Unlock()
	fake.SourcesClientStub = nil
	fake.sourcesClientReturns = struct {
		result1 v1alpha1.SourcesV1alpha1Interface
	}{result1}
}

func (fake *FakeKnSourceClient) SourcesClientReturnsOnCall(i int, result1 v1alpha1.SourcesV1alpha1Interface) {
	fake.sourcesClientMutex.Lock()
	defer fake.sourcesClientMutex.Unlock()
	fake.SourcesClientStub = nil
	if fake.sourcesClientReturnsOnCall == nil {
		fake.sourcesClientReturnsOnCall = make(map[int]struct {
			result1 v1alpha1.SourcesV1alpha1Interface
		})
	}
	fake.sourcesClientReturnsOnCall[i] = struct {
		result1 v1alpha1.SourcesV1alpha1Interface
	}{result1}
}

func (fake *FakeKnSourceClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.knSourceParamsMutex.RLock()
	defer fake.knSourceParamsMutex.RUnlock()
	fake.namespaceMutex.RLock()
	defer fake.namespaceMutex.RUnlock()
	fake.sourcesClientMutex.RLock()
	defer fake.sourcesClientMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeKnSourceClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.KnSourceClient = new(FakeKnSourceClient)
